parserOptions:
  ecmaVersion: 6

extends:
  - standard

plugins:
  - html

env:
  browser: true
  node: true

globals:

rules:
  no-unused-vars: 0
  indent:
    - 1
    - 2
  prefer-const:
    - 1
    - destructuring: all
